# Generated by Django 4.2.7 on 2024-03-04 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_worker', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('works', 'Works'), ('sick', 'Sick'), ('not_working_today', 'Not Working Today'), ('on_holiday', 'On Holiday'), ('pending', 'Pending')], default='available', max_length=20)),
                ('worker_name', models.CharField(default='', max_length=255)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfoliosite.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('garbage_image', models.ImageField(upload_to='garbage_images/')),
                ('street_image', models.ImageField(upload_to='street_images/')),
                ('commentary', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('deleted', 'Deleted by Administrator')], default='queued', max_length=20)),
                ('issue_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(default='', max_length=255)),
                ('report_name', models.CharField(default='', max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliosite.report')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoliosite.worker')),
            ],
        ),
    ]
