# Generated by Django 4.2.7 on 2024-03-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='garbage_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='street_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
